#!/bin/bash
#
# apache install
#
# kontrollime kas apache on paigaldatud 
Apache2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c 'ok installed')
# antud kasu tulemusena on kas 0 voi 1
if [ $Apache2 -eq 0 ]
then 
echo "Paigaldan apache2"
apt-get install -y apache2;
elif [ $Apache2 -eq 1 ]
then
echo "apache2 on paigaldatud!"
service apache2 status
fi
