#!/bin/bash
#
# Mysql serveri intallimine

mysql=$(dpkg-query -W -f='${Status}' mysql-server-5.7 2>/dev/null | grep -c "ok")

if [ $mysql -eq 0 ]
then
echo "mysql paigaldamine"
sudo apt-get install -y mysql-server-5.7

elif [ $mysql -eq 1 ]
then
echo "mysql on installitud"
/etc/init.d/mysql status
fi
