#!/bin/bash
#
# php installimine skriptiga
#
# Kontrollime kas php on installitud
php=$(dpkg-query -W -f='${Status}' php7.0 2>/dev/null | grep -c "ok installed")
# Antud ksu tulemusena on 0 vi 1
if [ $php -eq 0 ]
then
echo "Paigaldame php"
apt-get install -y php7.0 libapache2-mod-php7.0 php7.0-cli php7.0-mysql php7.0-curl php7.0-gd php7.0-mbstring php7.0-mcrypt php7.0-xml;
# kui ridade arv on 1, siis teenus on paigaldatud
elif [ $php -eq 1 ]
then
echo "php on paigaldatud!"
# laseme staatuse näitamist
php -v
fi

